api_controllers:
    resource:
        path: ../src/Infrastructure/ApiRest/
        namespace: App\Infrastructure\ApiRest
    type: attribute

web_controllers:
    resource:
        path: ../src/Infrastructure/Http/
        namespace: App\Infrastructure\Http
    type: attribute

